"""Auto-generate strategy proposal markdown from scored papers.

Generates markdown documents matching the format used in
research/strategies/ (e.g., vol_scaled_momentum.md). All auto-generated
proposals are tagged with [CEREBRO-AUTO] for easy identification.
"""

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from cerebro.config import cerebro_config

logger = logging.getLogger(__name__)


# Strategy proposal markdown template
PROPOSAL_TEMPLATE = """\
# [CEREBRO-AUTO] Strategy: {strategy_name}

> **Source:** {source} | **Asset Class:** {asset_classes} | **Composite Score:** {composite:.1f}/100 | **Auto-generated:** {date}

## Provenance

- **Paper:** {paper_title}
- **Authors:** {authors}
- **URL:** {url}
- **DOI:** {doi}
- **Published:** {published_date}
- **Discovered:** {discovered_date}

## Economic Rationale

{methodology}

### Key Findings

{key_findings}

## Signal Construction

{signal_description}

### Data Requirements

{data_requirements}

## Universe & Data Requirements

- **Asset Class:** {asset_classes}
- **Data Sources Needed:** {data_requirements_inline}
- **Backtest Period (paper):** {backtest_period}
- **Sample Size (paper):** {sample_size}

## Expected Performance

| Metric | Paper Reports |
|--------|--------------|
| Expected Sharpe | {expected_sharpe} |
| Out-of-Sample Tested | {oos_tested} |
| Transaction Costs Modeled | {costs_modeled} |

## Implementation Complexity

**Complexity:** {complexity}

**Estimated Effort:** {effort_days} days

### Feasibility Assessment

{feasibility_section}

## Risks & Limitations

{limitations}

## Novelty Assessment

{novelty_section}

## Scoring Breakdown

| Dimension | Score |
|-----------|-------|
| Relevance | {relevance:.1f}/100 |
| Quality | {quality:.1f}/100 |
| Novelty | {novelty:.1f}/100 |
| **Composite** | **{composite:.1f}/100** |

## Next Steps

- [ ] Domain review by Elena/Marco
- [ ] PM verdict
- [ ] Fix any blocking framework bugs before backtesting
- [ ] Pre-commit signal parameters before optimization
- [ ] Walk-forward OOS validation
- [ ] Paper trade 3 months minimum

---
*Auto-generated by Cerebro on {date}. Requires human review before any capital allocation.*
"""


class ProposalGenerator:
    """Generate strategy proposal markdown from scored papers.

    Outputs markdown files matching the format in research/strategies/,
    tagged with [CEREBRO-AUTO] for traceability.
    """

    def __init__(
        self,
        output_dir: Optional[str] = None,
    ) -> None:
        """Initialize the proposal generator.

        Args:
            output_dir: Directory to write proposals to.
                Defaults to research/strategies/ in project root.
        """
        project_root = cerebro_config.project_root
        self._output_dir = Path(
            output_dir or str(project_root / "research" / "strategies")
        )

    def generate(self, scored_paper) -> str:
        """Generate a strategy proposal markdown document.

        Args:
            scored_paper: ScoredPaper instance with paper, summary, and scores.

        Returns:
            Markdown string of the full proposal.
        """
        paper = scored_paper.paper
        summary = scored_paper.summary

        strategy_name = self._derive_strategy_name(summary)

        # Build section content
        key_findings = self._format_bullet_list(summary.key_findings)
        limitations = self._format_bullet_list(summary.limitations)
        data_requirements = self._format_bullet_list(summary.data_requirements)
        feasibility_section = self._build_feasibility_section(summary)
        novelty_section = self._build_novelty_section(scored_paper)

        content = PROPOSAL_TEMPLATE.format(
            strategy_name=strategy_name,
            source=paper.source.upper(),
            asset_classes=", ".join(summary.asset_class)
            if summary.asset_class
            else "Not specified",
            composite=scored_paper.composite_score,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            paper_title=paper.title,
            authors=", ".join(paper.authors) if paper.authors else "Unknown",
            url=paper.url,
            doi=paper.doi or "N/A",
            published_date=(
                paper.published_date.strftime("%Y-%m-%d")
                if paper.published_date
                else "Unknown"
            ),
            discovered_date=(
                paper.fetched_at.strftime("%Y-%m-%d")
                if paper.fetched_at
                else datetime.utcnow().strftime("%Y-%m-%d")
            ),
            methodology=summary.methodology or "Not extracted from paper.",
            key_findings=key_findings or "- No key findings extracted.",
            signal_description=summary.signal_description
            or "No explicit signal described in the paper.",
            data_requirements=data_requirements
            or "- No specific data requirements identified.",
            data_requirements_inline=(
                ", ".join(summary.data_requirements)
                if summary.data_requirements
                else "Not specified"
            ),
            backtest_period=summary.backtest_period or "Not reported",
            sample_size=summary.sample_size or "Not reported",
            expected_sharpe=(
                f"{summary.expected_sharpe:.2f}"
                if summary.expected_sharpe is not None
                else "Not reported"
            ),
            oos_tested="Yes" if summary.out_of_sample else "No",
            costs_modeled="Yes" if summary.transaction_costs_modeled else "No",
            complexity=summary.implementation_complexity,
            effort_days=self._estimate_effort(summary),
            feasibility_section=feasibility_section,
            limitations=limitations or "- No limitations noted.",
            novelty_section=novelty_section,
            relevance=scored_paper.relevance_score,
            quality=scored_paper.quality_score,
            novelty=scored_paper.novelty_score,
        )

        return content

    def save_proposal(self, content: str, scored_paper) -> str:
        """Save a proposal to the output directory and update the tracker.

        File name format: auto_<date>_<slug>.md

        Also appends a new entry to research/STRATEGY_TRACKER.md so
        auto-generated proposals appear in the master pipeline table.

        Args:
            content: Markdown content string.
            scored_paper: ScoredPaper (used for slug derivation).

        Returns:
            Absolute path to the saved file.
        """
        self._output_dir.mkdir(parents=True, exist_ok=True)

        date_str = datetime.utcnow().strftime("%Y%m%d")
        slug = self._slugify(scored_paper.paper.title)
        filename = f"auto_{date_str}_{slug}.md"

        filepath = self._output_dir / filename
        filepath.write_text(content, encoding="utf-8")

        logger.info("Saved proposal: %s", filepath)

        # Update the strategy tracker
        self._update_strategy_tracker(scored_paper, filename)

        return str(filepath)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _derive_strategy_name(summary) -> str:
        """Derive a short strategy name from the summary.

        Args:
            summary: PaperSummary instance.

        Returns:
            Human-readable strategy name.
        """
        one_line = summary.one_line or summary.title
        # Take first ~60 chars and clean up
        name = one_line[:60].strip()
        if len(one_line) > 60:
            # Try to break at a word boundary
            last_space = name.rfind(" ")
            if last_space > 30:
                name = name[:last_space]
        return name

    @staticmethod
    def _format_bullet_list(items: tuple) -> str:
        """Format a tuple of strings as a markdown bullet list.

        Args:
            items: Tuple of strings.

        Returns:
            Markdown bullet list string.
        """
        if not items:
            return ""
        return "\n".join(f"- {item}" for item in items)

    @staticmethod
    def _build_feasibility_section(summary) -> str:
        """Build the feasibility assessment section.

        Args:
            summary: PaperSummary instance.

        Returns:
            Markdown string for feasibility section.
        """
        from cerebro.scoring.feasibility_scorer import FeasibilityScorer

        scorer = FeasibilityScorer()
        result = scorer.assess(summary)

        lines = []
        status = "FEASIBLE" if result.is_feasible else "NOT FEASIBLE"
        lines.append(f"**Status:** {status} (confidence: {result.confidence:.0%})")
        lines.append("")

        if result.enablers:
            lines.append("**Enablers:**")
            for e in result.enablers:
                lines.append(f"- {e}")
            lines.append("")

        if result.blockers:
            lines.append("**Blockers:**")
            for b in result.blockers:
                lines.append(f"- {b}")
            lines.append("")

        if result.missing_data:
            lines.append("**Missing Data:**")
            for d in result.missing_data:
                lines.append(f"- {d}")

        return "\n".join(lines)

    @staticmethod
    def _build_novelty_section(scored_paper) -> str:
        """Build the novelty assessment section.

        Args:
            scored_paper: ScoredPaper instance.

        Returns:
            Markdown string for novelty section.
        """
        novelty_score = scored_paper.novelty_score

        if novelty_score >= 70:
            classification = "NOVEL"
            desc = "This paper presents a genuinely new approach."
        elif novelty_score >= 40:
            classification = "INCREMENTAL"
            desc = "Builds on existing work with meaningful improvements."
        else:
            classification = "REHASH"
            desc = "Very similar to existing papers in corpus."

        return (
            f"**Classification:** {classification} "
            f"(novelty score: {novelty_score:.1f}/100)\n\n"
            f"{desc}"
        )

    @staticmethod
    def _estimate_effort(summary) -> int:
        """Estimate implementation effort in days.

        Args:
            summary: PaperSummary instance.

        Returns:
            Estimated effort in person-days.
        """
        base = {"LOW": 3, "MEDIUM": 7, "HIGH": 15}
        return base.get(summary.implementation_complexity, 7)

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert text to a filesystem-safe slug.

        Args:
            text: Input text.

        Returns:
            Lowercase slug with underscores.
        """
        # Remove non-alphanumeric characters, replace spaces with underscores
        slug = re.sub(r"[^\w\s-]", "", text.lower())
        slug = re.sub(r"[\s-]+", "_", slug).strip("_")
        # Truncate to reasonable length
        return slug[:50]

    def _update_strategy_tracker(self, scored_paper, filename: str) -> None:
        """Append a new entry to research/STRATEGY_TRACKER.md.

        Inserts a row into the Strategy Pipeline table. Uses immutable
        string operations (no in-place mutation of tracker content).

        Args:
            scored_paper: ScoredPaper with paper info and scores.
            filename: Name of the proposal file (for reference).
        """
        tracker_path = cerebro_config.project_root / "research" / "STRATEGY_TRACKER.md"

        if not tracker_path.exists():
            logger.warning(
                "STRATEGY_TRACKER.md not found at %s; skipping update",
                tracker_path,
            )
            return

        try:
            existing_content = tracker_path.read_text(encoding="utf-8")

            # Derive the next strategy number from existing rows
            row_pattern = re.compile(r"^\|\s*(\d+)\s*\|", re.MULTILINE)
            existing_numbers = [
                int(m.group(1)) for m in row_pattern.finditer(existing_content)
            ]
            next_number = max(existing_numbers, default=0) + 1

            summary = scored_paper.summary
            asset_classes = (
                ", ".join(summary.asset_class) if summary.asset_class else "Unknown"
            )
            strategy_name = self._derive_strategy_name(summary)
            # Truncate for table readability
            short_name = strategy_name[:40] + ("..." if len(strategy_name) > 40 else "")

            new_row = (
                f"| {next_number} | [CEREBRO] {short_name} | Cerebro | "
                f"{asset_classes} | PENDING REVIEW | — | "
                f"Auto-generated ({filename}) |"
            )

            # Insert row before the "## Blocking Requirements" section
            marker = "## Blocking Requirements"
            if marker in existing_content:
                parts = existing_content.split(marker, 1)
                updated_content = (
                    parts[0].rstrip() + "\n" + new_row + "\n\n" + marker + parts[1]
                )
            else:
                # Fallback: append before the last "---" separator
                last_sep = existing_content.rfind("\n---")
                if last_sep != -1:
                    updated_content = (
                        existing_content[:last_sep].rstrip()
                        + "\n"
                        + new_row
                        + "\n"
                        + existing_content[last_sep:]
                    )
                else:
                    updated_content = (
                        existing_content.rstrip() + "\n\n" + new_row + "\n"
                    )

            # Update the "Last updated" timestamp
            date_str = datetime.utcnow().strftime("%Y-%m-%d")
            updated_content = re.sub(
                r"\*Last updated: \d{4}-\d{2}-\d{2}\*",
                f"*Last updated: {date_str}*",
                updated_content,
            )

            tracker_path.write_text(updated_content, encoding="utf-8")
            logger.info(
                "Updated STRATEGY_TRACKER.md with entry #%d: %s",
                next_number,
                short_name,
            )
        except Exception as exc:
            logger.error("Failed to update STRATEGY_TRACKER.md: %s", exc)
