#!/usr/bin/env python3
"""Integrity check (and index generator) for the research second brain.

    python3 scripts/check_brain_integrity.py              # validate
    python3 scripts/check_brain_integrity.py --reindex    # rewrite CONCEPTS.md, then validate

Why this exists: five of the six condensation layers in this repo died because their
conventions were documented but never enforced, and the one that survived had a
checker. The mechanism pool has its own (check_ideas_integrity.py); this covers the
concept and verdict layers and the links between all three.

Invariants:
  - concept/verdict IDs unique, and the ID matches the filename and the frontmatter
  - required frontmatter present on every concept
  - every verdict has an HTML anchor matching its ID
  - [[wikilinks]] resolve to a real note in the vault
  - relative markdown links resolve (file, and #idea-NNN / #verdict-NNN anchors)
  - CONCEPTS.md index matches concepts/ on disk
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAIN = ROOT / "knowledge/brain"
CONCEPTS_DIR = BRAIN / "concepts"
INDEX = BRAIN / "CONCEPTS.md"
VERDICTS = BRAIN / "VERDICTS.md"
IDEAS = ROOT / "knowledge/reports/IDEAS.md"

REQUIRED_FM = ("type", "id", "slug", "domain", "status")
VALID_STATUS = {"stable", "contested", "unsettled"}

# Capture transport lives OUTSIDE the repo on purpose: this repo is public, and a raw
# captured thought must not become a public commit. See brain/CAPTURE.md.
CAPTURES = pathlib.Path.home() / "Dropbox/thought-inbox"
CAPTURE_NAME = re.compile(r"^\d{4}-\d{2}-\d{2}-\d{4}-[a-z0-9][a-z0-9-]*\.md$", re.I)
CAPTURE_REQUIRED = ("type", "captured", "status")
CAPTURE_STATUS = {"open", "triaged", "dropped"}
CAPTURE_SOURCE = {"shortcut", "voice", "share", "manual"}


def frontmatter(text):
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    out = {}
    for line in text[4:end].split("\n"):
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip()
    return out


def load_concepts():
    out = []
    for f in sorted(CONCEPTS_DIR.glob("CONCEPT-*.md")):
        text = f.read_text(encoding="utf-8")
        out.append((f, frontmatter(text), text))
    return out


def reindex(concepts):
    rows = []
    for f, fm, text in concepts:
        m = re.search(r"^\*\*Definition\.\*\*\s*(.+?)(?:\n\n|\Z)", text, re.M | re.S)
        gist = " ".join(m.group(1).split())[:150] if m else ""
        if len(gist) == 150:
            gist = gist.rsplit(" ", 1)[0] + "…"
        rows.append(
            f"| [{fm.get('id','?')}]({f.parent.name}/{f.name}) | "
            f"`{fm.get('domain','?')}` | **{fm.get('slug','?')}** | "
            f"`{fm.get('status','?')}` | {gist} |"
        )
    by_domain = {}
    for _f, fm, _t in concepts:
        by_domain.setdefault(fm.get("domain", "?"), 0)
        by_domain[fm["domain"]] += 1
    comp = " · ".join(f"{v} {k}" for k, v in sorted(by_domain.items()))
    INDEX.write_text(
        "# CONCEPTS — index\n\n"
        "*Generated by `python3 scripts/check_brain_integrity.py --reindex`. Do not hand-edit.*\n\n"
        "The durable machinery that mechanisms are built from. One atom per note in "
        "[`concepts/`](concepts/); `status` is `stable` (settled), `contested` (real but "
        "regime- or estimator-dependent) or `unsettled` (open question).\n\n"
        f"**{len(concepts)} concepts** — {comp}\n\n"
        "| ID | Domain | Concept | Status | Definition |\n"
        "|---|---|---|---|---|\n" + "\n".join(rows) + "\n\n"
        "See [`README.md`](README.md) for the ladder and the three atom types, "
        "[`../reports/IDEAS.md`](../reports/IDEAS.md) for mechanisms, "
        "[`VERDICTS.md`](VERDICTS.md) for tested outcomes.\n",
        encoding="utf-8",
    )
    print(f"reindexed {INDEX.relative_to(ROOT)} ({len(concepts)} concepts)")


def check_captures(known_ids, known_domains):
    """Validate the capture transport dir. Silent no-op when it does not exist."""
    problems = []
    if not CAPTURES.exists():
        return problems, 0
    n = 0
    for f in sorted(CAPTURES.glob("*.md")):
        if f.name == "README.md":
            continue
        n += 1
        rel = f.name
        if not CAPTURE_NAME.match(f.name):
            problems.append(f"capture {rel}: filename must be YYYY-MM-DD-HHMM-slug.md")
        text = f.read_text(encoding="utf-8")
        fm = frontmatter(text)
        for key in CAPTURE_REQUIRED:
            if not fm.get(key):
                problems.append(f"capture {rel}: missing frontmatter '{key}'")
        if fm.get("type") and fm["type"] != "capture":
            problems.append(f"capture {rel}: type is '{fm['type']}', must be 'capture'")
        if fm.get("status") and fm["status"] not in CAPTURE_STATUS:
            problems.append(
                f"capture {rel}: status '{fm['status']}' not in {sorted(CAPTURE_STATUS)}"
            )
        if fm.get("source") and fm["source"] not in CAPTURE_SOURCE:
            problems.append(
                f"capture {rel}: source '{fm['source']}' not in {sorted(CAPTURE_SOURCE)}"
            )
        if fm.get("lens") and fm["lens"] not in known_domains:
            problems.append(
                f"capture {rel}: lens '{fm['lens']}' is not an existing concept domain "
                f"({sorted(known_domains)}) — a phone may not invent vocabulary"
            )
        for rid in re.findall(r"(?:IDEA|CONCEPT|VERDICT)-\d{3}", fm.get("refs", "")):
            if rid not in known_ids:
                problems.append(f"capture {rel}: refs cites unknown {rid}")
        body = text.split("\n---", 1)[-1] if text.startswith("---") else text
        for bad, why in (("[[", "wikilink"), ("](", "markdown link")):
            if bad in body:
                problems.append(
                    f"capture {rel}: body contains a {why} — captures may not create edges; "
                    "relating happens at triage where both sides can be written"
                )
    return problems, n


def main() -> int:
    problems = []
    if not BRAIN.exists():
        print(f"FAIL  {BRAIN} not found")
        return 1

    concepts = load_concepts()
    if "--reindex" in sys.argv:
        reindex(concepts)

    # ---- concepts: ids, filenames, frontmatter
    seen = {}
    for f, fm, text in concepts:
        cid = fm.get("id", "")
        for key in REQUIRED_FM:
            if not fm.get(key):
                problems.append(f"{f.name}: missing frontmatter '{key}'")
        if fm.get("status") and fm["status"] not in VALID_STATUS:
            problems.append(
                f"{f.name}: status '{fm['status']}' not in {sorted(VALID_STATUS)}"
            )
        if not f.name.startswith(cid + "-"):
            problems.append(f"{f.name}: filename does not start with its id '{cid}'")
        if fm.get("slug") and not f.stem.endswith(fm["slug"]):
            problems.append(f"{f.name}: filename does not end with slug '{fm['slug']}'")
        if cid in seen:
            problems.append(f"duplicate id {cid}: {f.name} and {seen[cid]}")
        seen[cid] = f.name
        if not re.search(rf"^# {re.escape(cid)} · ", text, re.M):
            problems.append(f"{f.name}: no '# {cid} · ...' heading")

    # ---- verdicts: ids unique and anchored
    vtext = VERDICTS.read_text(encoding="utf-8") if VERDICTS.exists() else ""
    vids = re.findall(r"^### (VERDICT-\d{3}) · ", vtext, re.M)
    vanchors = set(re.findall(r'<a id="(verdict-\d+)">', vtext))
    for v in vids:
        if v.lower() not in vanchors:
            problems.append(f"{v} has no anchor in VERDICTS.md")
    dupes = {v for v in vids if vids.count(v) > 1}
    if dupes:
        problems.append(f"duplicate verdict ids: {sorted(dupes)}")

    # ---- link targets
    idea_anchors = set()
    if IDEAS.exists():
        idea_anchors = set(
            re.findall(r'<a id="(idea-\d+)">', IDEAS.read_text(encoding="utf-8"))
        )
    vault = ROOT
    # Obsidian resolves [[stem]] by shortest-path-wins; a dict built with setdefault
    # resolves by whichever rglob hit first, which is NOT the same rule. 34 stems collide
    # among the 296 notes Obsidian indexes (README, FINDINGS_LOG, reading_queue, ...), so
    # treat an ambiguous target as a failure rather than silently picking one.
    notes_by_stem = {}
    for p in vault.rglob("*.md"):
        if any(part.startswith(".") for part in p.relative_to(vault).parts):
            continue
        notes_by_stem.setdefault(p.stem, []).append(p)

    md_link = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
    wiki = re.compile(r"\[\[([^\]|#]+)")
    inline_code = re.compile(r"`[^`]*`")
    checked = 0
    for f in sorted(BRAIN.rglob("*.md")):
        in_fence = False
        for lineno, raw_line in enumerate(f.read_text(encoding="utf-8").split("\n"), 1):
            # Documentation must be able to SHOW a link without the scanner treating it as
            # one. Skip fenced blocks and strip inline code spans before matching.
            if raw_line.lstrip().startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            line = inline_code.sub("", raw_line)
            for target in wiki.findall(line):
                hits = notes_by_stem.get(target.strip(), [])
                if not hits:
                    problems.append(
                        f"{f.relative_to(BRAIN)}:{lineno} dead wikilink [[{target}]]"
                    )
                elif len(hits) > 1:
                    where = ", ".join(str(h.relative_to(vault)) for h in hits[:3])
                    problems.append(
                        f"{f.relative_to(BRAIN)}:{lineno} ambiguous wikilink [[{target}]] "
                        f"resolves to {len(hits)} notes ({where})"
                    )
                else:
                    checked += 1
            for _label, target in md_link.findall(line):
                if target.startswith(("http://", "https://", "mailto:")):
                    continue
                path, _, frag = target.partition("#")
                dest = (f.parent / path).resolve() if path else f
                if path and not dest.exists():
                    problems.append(
                        f"{f.relative_to(BRAIN)}:{lineno} dead link {target}"
                    )
                    continue
                if (
                    frag.startswith("idea-")
                    and idea_anchors
                    and frag not in idea_anchors
                ):
                    problems.append(
                        f"{f.relative_to(BRAIN)}:{lineno} dead anchor {target}"
                    )
                    continue
                if frag.startswith("verdict-") and frag not in vanchors:
                    problems.append(
                        f"{f.relative_to(BRAIN)}:{lineno} dead anchor {target}"
                    )
                    continue
                checked += 1

    # ---- index matches disk
    if INDEX.exists():
        indexed = set(
            re.findall(r"\[(CONCEPT-\d{3})\]", INDEX.read_text(encoding="utf-8"))
        )
        on_disk = {fm.get("id") for _f, fm, _t in concepts}
        if indexed != on_disk:
            problems.append(
                f"CONCEPTS.md out of sync: index {sorted(indexed - on_disk)} extra, "
                f"{sorted(on_disk - indexed)} missing — run --reindex"
            )
    else:
        problems.append("CONCEPTS.md missing — run --reindex")

    # ---- capture transport (opt-in: --captures)
    ncap = 0
    if "--captures" in sys.argv:
        known_ids = (
            set(
                re.findall(
                    r"^### (IDEA-\d{3}) · ", IDEAS.read_text(encoding="utf-8"), re.M
                )
            )
            if IDEAS.exists()
            else set()
        )
        known_ids |= {fm.get("id") for _f, fm, _t in concepts if fm.get("id")}
        known_ids |= set(vids)
        known_domains = {
            fm.get("domain") for _f, fm, _t in concepts if fm.get("domain")
        }
        cap_problems, ncap = check_captures(known_ids, known_domains)
        problems.extend(cap_problems)

    if problems:
        print(f"FAIL  {len(problems)} problem(s) in the brain:")
        for p in problems:
            print(f"  - {p}")
        return 1
    tail = f" · {ncap} captures valid" if "--captures" in sys.argv else ""
    print(
        f"OK    {len(concepts)} concepts · {len(vids)} verdicts · "
        f"{checked} links live · index in sync{tail}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
